name: Build Windows Executable

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build frontend
      run: npm run build
    
    - name: Build server
      run: npm run build:server
    
    - name: Build Electron app
      run: npm run build:electron
    
    - name: Package Windows installer
      run: npm run package:win
    
    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: AMPaints-Windows-Installer
        path: dist-installer/*.exe
        retention-days: 30
